/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./frontend/index.html",
    "./frontend/src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f9f9ff",
        "surface-container-low": "#f1f3ff",
        "error": "#ba1a1a",
        "brand-accent-glow": "#3B82F6",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#818486",
        "surface-bright": "#f9f9ff",
        "status-success": "#22C55E",
        "surface-tint": "#565e74",
        "text-secondary": "#475569",
        "on-background": "#141b2b",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#00174b",
        "secondary-fixed": "#dbe1ff",
        "error-container": "#ffdad6",
        "primary": "#000000",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#bec6e0",
        "on-surface": "#141b2b",
        "on-primary-fixed": "#131b2e",
        "surface-variant": "#dce2f7",
        "inverse-on-surface": "#edf0ff",
        "primary-fixed-dim": "#bec6e0",
        "outline-variant": "#c6c6cd",
        "on-secondary-fixed-variant": "#003ea8",
        "on-surface-variant": "#45464d",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "outline": "#76777d",
        "surface": "#f9f9ff",
        "tertiary-fixed-dim": "#c4c7c9",
        "tertiary": "#000000",
        "secondary-container": "#316bf3",
        "surface-container-high": "#e1e8fd",
        "tertiary-fixed": "#e0e3e5",
        "on-primary-container": "#7c839b",
        "on-tertiary-fixed-variant": "#444749",
        "legacy-red": "#BE1E2D",
        "secondary": "#0051d5",
        "on-secondary-container": "#fefcff",
        "on-primary": "#ffffff",
        "surface-dim": "#d3daef",
        "on-error": "#ffffff",
        "tertiary-container": "#191c1e",
        "on-tertiary-fixed": "#191c1e",
        "inverse-surface": "#293040",
        "surface-container-highest": "#dce2f7",
        "surface-container": "#e9edff",
        "primary-container": "#131b2e",
        "primary-fixed": "#dae2fd"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "gutter": "24px",
        "base": "8px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "section-gap": "120px"
      },
      fontFamily: {
        "ui-label-bold": ["Plus Jakarta Sans", "sans-serif"],
        "title-sm": ["Libre Caslon Text", "serif"],
        "display-lg-mobile": ["Libre Caslon Text", "serif"],
        "ui-caption": ["Plus Jakarta Sans", "sans-serif"],
        "ui-label-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Libre Caslon Text", "serif"],
        "headline-md-mobile": ["Libre Caslon Text", "serif"],
        "headline-md": ["Libre Caslon Text", "serif"],
        "body-lg": ["Libre Caslon Text", "serif"],
        "body-md": ["Libre Caslon Text", "serif"]
      },
      fontSize: {
        "ui-label-bold": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "700" }],
        "title-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "ui-caption": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "ui-label-md": ["14px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md-mobile": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-md": ["30px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
